# Generated by Django 5.1.3 on 2024-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
                ('snum', models.FloatField()),
                ('scourse', models.CharField(max_length=100)),
                ('sadd', models.CharField(max_length=200)),
            ],
        ),
    ]
